"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

from decouple import config, Csv


import os
import redis


load_dotenv()  # load all environment variables from .env file (or on Heroku for production) into the process environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print("BASE_DIR:", BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-b3m=h8+s34wjn@z068ppzswtpm8ujo#ix7(*h$=tdcfa+wvbs-'
SECRET_KEY = config('SECRET_KEY', default='unsafe-secret-key-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = config('DEBUG', default=False, cast=bool)
DEBUG = config('DEBUG', default=False, cast=bool)

# allow any host to host our django app
# will change this in production to specific domain names ...herokuapp.com, etc.
#ALLOWED_HOSTS = ["*"]
#ALLOWED_HOSTS = ["kpbackend-423a8e253858.herokuapp.com", "127.0.0.1", "localhost"]
#


ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
#print ALLOWED_HOSTS (which comes from .env) for debugging
print("ALLOWED_HOSTS:", ALLOWED_HOSTS)

CORS_ALLOWED_ORIGINS =  config('CORS_ALLOWED_ORIGINS', cast=Csv())
# ('CORS_ALLOWED_ORIGINS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'api.apps.ApiConfig',
    'english.apps.EnglishConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_extensions'
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

APPEND_SLASH = True    # handle trailing slashes in URLs

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Get the URL from Heroku environment
REDIS_URL = os.environ.get('REDIS_URL')
print("REDIS_URL:", REDIS_URL)
# redis://localhost:6379/0
# if REDIS_URL has a 'localhost' string,  don't ssl_cert_que


# 1. Get the URL from environment or default to local
REDIS_URL = os.environ.get('REDISCLOUD_URL', 'redis://127.0.0.1:6379')

# 2. Define the global connection variable
R_CONN = redis.from_url(REDIS_URL, decode_responses=True)


"""
if REDIS_URL and 'rediss' in REDIS_URL:  # if REDIS_URL is defined and uses rediss:// scheme, then it's likely a production environment that requires SSL
      R_CONN = redis.StrictRedis.from_url(
        REDIS_URL, 
        decode_responses=True,
        ssl_cert_reqs=None
    )
else:   # development environment, or production environment that doesn't require SSL (e.g. Redis Cloud with TLS disabled)
     R_CONN = redis.StrictRedis.from_url(
        REDIS_URL, 
        decode_responses=True,
    )
"""

"""
if REDIS_URL:
    # On Heroku, we need to disable SSL certificate verification
    # because Heroku uses self-signed certificates.
    R_CONN = redis.StrictRedis.from_url(
        REDIS_URL, 
        decode_responses=True,
        ssl_cert_reqs=None
    )
else:
    # Fallback for local development
    R_CONN = redis.Redis(host='localhost', port=6379, db=0)
"""

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://kevinpham:ttrami120110@localhost:5432/fullstack1',
        conn_max_age=600,  # Optional: enable connection pooling
        ssl_require=False  # Set to True if your production database requires SSL
    )
}


#print("DATABASE URL in use:", os.getenv('DATABASE_CONNECTION_POOL_URL', 'Default DATABASE_URL'))
#print("Database configuration:", DATABASES['default'])

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",  # Your frontend's origin
    "http://localhost:5175", 
    "http://localhost:5173",
    'https://phuyenenglish.com',
    'https://www.phuyenenglish.com',   # in HEROKU, need this to avoid error when connecting web socket with wss. Feb 4, 2026, kpham
    "https://wwww.tienganhphuyen.com", 
    "https://tienganhphuyen.com",
    "https://wwww.kevinphamenglish.com",
    "https://kevinphamenglish.com",
    "https://magnificent-figolla-d3b835.netlify.app",
    "https://magnificent-custard-cc8e68.netlify.com",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = [
    'https://kp-ws-redis-7c251d3f5802.herokuapp.com/',
    'https://phuyenenglish.com',
    'https://www.phuyenenglish.com',
    'https://tienganhphuyen.com',
    'https://www.tienganhphuyen.com',
    'https://kevinphamenglish.com',
    'https://www.kevinphamenglish.com',
    'https://magnificent-figolla-d3b835.netlify.app',
    'https://magnificent-custard-cc8e68.netlify.com',
    'http://localhost:5174',
    'http://127.0.0.1:8000',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"

