"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
import ssl

import os
import urllib.parse


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print("BASE_DIR:", BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b3m=h8+s34wjn@z068ppzswtpm8ujo#ix7(*h$=tdcfa+wvbs-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# allow any host to host our django app
# will change this in production to specific domain names ...herokuapp.com, etc.
#ALLOWED_HOSTS = ["*"]
#ALLOWED_HOSTS = ["kpbackend-423a8e253858.herokuapp.com", "127.0.0.1", "localhost"]
#
ALLOWED_HOSTS = ["django-with-redis-c6f7d6ccaf6e.herokuapp.com", 
                 "127.0.0.1", "localhost",
                 'magnificent-figolla-d3b835.netlify.app', # Add your frontend domain!
                 'tienganhphuyen.com',
                 'wwww.tienganhphuyen.com',
                 ]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",  # Your frontend's origin
    "http://localhost:5175", 
    "http://localhost:5173",
    "https://magnificent-figolla-d3b835.netlify.app",  # Your frontend domain
    "https://wwww.tienganhphuyen.com",
    "https://tienganhphuyen.com",
    "https://wwww.kevinphamenglish.com",
    "https://kevinphamenglish.com",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'api.apps.ApiConfig',
    'english.apps.EnglishConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_extensions'
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

APPEND_SLASH = True    # handle trailing slashes in URLs

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



#WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"

# Fallback to local Redis if REDIS_URL environment variable isn't set
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Parse the URL to check the protocol
url = urllib.parse.urlparse(REDIS_URL)
#print("Parsed REDIS_URL:", url)
#print(" Scheme:", url.scheme)
#print("REDIS_URL:", REDIS_URL)
# 3. Configure CHANNEL_LAYERS to use Redis
"""
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],  # Use the REDIS_URL directly
            "redis_config": {
                "ssl_cert_reqs": None, # Disables SSL certificate verification
            }
        },
    },
}
"""

import os
import urllib.parse

# 1. Parse the Redis URL provided by Heroku
#redis_url = urllib.parse.urlparse(os.environ.get('REDIS_URL'))

"""
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": REDIS_URL,
                # Use SSL settings ONLY if the protocol is 'rediss'
                "ssl_cert_reqs": None if url.scheme == "rediss" else None,
            }],
        },
    },
}

print("CHANNEL_LAYERS:", CHANNEL_LAYERS)
"""

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')
url = urllib.parse.urlparse(REDIS_URL)

# --- Base Redis Configuration ---
# Use db 0 for Cache, db 1 for Channels
cache_url = f"{REDIS_URL}/0"
channels_url = f"{REDIS_URL}/1"

# SSL Logic (Same as we did for Channel Layers)
ssl_options = {}
if url.scheme == 'rediss':
    ssl_options = {"ssl_cert_reqs": None}

# --- 1. CHANNEL_LAYERS Configuration ---


print("CACHES using REDIS_URL:", REDIS_URL)
print("URL scheme:", url.scheme)



is_ssl = url.scheme == 'rediss'

print("Is SSL required for Redis connections?", is_ssl)

# 2. Configure CACHES (Standard Django Cache)
# Use Heroku's URL if available, otherwise fallback to local Redis
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

import os

# Create the base cache config
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {}
    }
}

# Only add SSL bypass if we are using an 'rediss' (SSL) URL
if REDIS_URL.startswith('rediss'):
    CACHES["default"]["OPTIONS"]["ssl_cert_reqs"] = None

# 3. Configure CHANNEL_LAYERS (Django Channels / WebSockets)
"""
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            # Channels uses an SSL Context object rather than raw kwargs
            "ssl_context": ssl._create_unverified_context() if is_ssl else None,
        },
    },
}
"""

# We append the ssl_cert_reqs=none parameter directly to the URL 
# only if it's a production rediss:// URL
RAW_REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')
print("RAW_REDIS_URL:", RAW_REDIS_URL)

if RAW_REDIS_URL.startswith('rediss://'):
    # This adds the query parameter that tells the redis client to skip verification
    if "?" in RAW_REDIS_URL:
        CHANNEL_REDIS_URL = f"{RAW_REDIS_URL}&ssl_cert_reqs=none"
    else:
        CHANNEL_REDIS_URL = f"{RAW_REDIS_URL}?ssl_cert_reqs=none"
else:
    CHANNEL_REDIS_URL = RAW_REDIS_URL

print("CHANNEL_REDIS_URL:", CHANNEL_REDIS_URL)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
        },
    },
}




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(env='DATABASE_CONNECTION_POOL_URL',
        default='postgres://kevinpham:ttrami120110@localhost:5432/fullstack1',
        conn_max_age=600,  # Optional: enable connection pooling
        ssl_require=False  # Set to True if your production database requires SSL
    )
}

#print("DATABASE URL in use:", os.getenv('DATABASE_CONNECTION_POOL_URL', 'Default DATABASE_URL'))
#print("Database configuration:", DATABASES['default'])

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",  # Your frontend's origin
    "http://localhost:5175", 
    "http://localhost:5173",
    'https://phuyenenglish.com',
    'https://www.phuyenenglish.com',
    "https://wwww.tienganhphuyen.com",
    "https://tienganhphuyen.com",
    "https://wwww.kevinphamenglish.com",
    "https://kevinphamenglish.com",
    "https://magnificent-figolla-d3b835.netlify.app",
    "https://magnificent-custard-cc8e68.netlify.com",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = [
    'https://django-with-redis-c6f7d6ccaf6e.herokuapp.com',
    'https://phuyenenglish.com',
    'https://www.phuyenenglish.com',
    'https://tienganhphuyen.com',
    'https://www.tienganhphuyen.com',
    'https://kevinphamenglish.com',
    'https://www.kevinphamenglish.com',
    'https://magnificent-figolla-d3b835.netlify.app',
    'https://magnificent-custard-cc8e68.netlify.com',
    'http://localhost:5174',
    'http://127.0.0.1:8000',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"

