# Generated by Django 6.0.1 on 2026-01-20 23:17

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('api', 'Profile')
    for user in User.objects.all():
        # get_or_create prevents errors if a profile accidentally exists
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
