# Generated by Django 6.0.1 on 2026-01-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_videosegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosegment',
            name='end_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='videosegment',
            name='start_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='videosegment',
            name='video_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
