# Generated by Django 6.0.1 on 2026-01-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_videosegment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosegment',
            name='segment_number',
            field=models.IntegerField(default=0),
        ),
    ]
