# Generated by Django 6.0.1 on 2026-01-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_videosegment_segment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosegment',
            name='video_url',
        ),
    ]
