# Generated by Django 6.0.1 on 2026-01-31 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_videosegment_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosegment',
            name='question_numbers',
        ),
        migrations.AddField(
            model_name='question',
            name='video_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_segments', to='api.videosegment'),
        ),
    ]
