# Generated by Django 6.0.1 on 2026-01-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_videosegment_question_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
