# Generated by Django 6.0.1 on 2026-02-01 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quiz_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='video_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.videosegment'),
        ),
    ]
