# Generated by Django 6.0.1 on 2026-02-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_question_video_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
