# Generated by Django 6.0.1 on 2026-02-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_quiz_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
