# Generated by Django 6.0.1 on 2026-04-04 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_quiz_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_word', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pron_code', models.CharField(blank=True, max_length=50, null=True)),
                ('amevar_pron', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('grammar', models.CharField(blank=True, max_length=100, null=True)),
                ('dict_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of_speeches', to='api.dictentry')),
            ],
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(blank=True, max_length=700, null=True)),
                ('translation', models.TextField(blank=True, max_length=1000, null=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idioms', to='api.partofspeech')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_number', models.SmallIntegerField(default=0)),
                ('definition', models.TextField(blank=True, max_length=1000, null=True)),
                ('def_translation', models.TextField(blank=True, max_length=1000, null=True)),
                ('cross_reference', models.CharField(blank=True, max_length=400, null=True)),
                ('grammar', models.CharField(blank=True, max_length=80, null=True)),
                ('related_words', models.CharField(blank=True, max_length=200, null=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='api.partofspeech')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_number', models.SmallIntegerField(default=0)),
                ('difficulty_level', models.SmallIntegerField(default=0)),
                ('sentence', models.TextField(blank=True, max_length=1000, null=True)),
                ('translation', models.TextField(blank=True, max_length=1200, null=True)),
                ('grammar_point', models.CharField(blank=True, max_length=100, null=True)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='api.sense')),
            ],
        ),
    ]
