# Generated by Django 6.0.1 on 2026-04-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dictentry_partofspeech_idiom_sense_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='question_attempt_number',
            field=models.IntegerField(default=0),
        ),
    ]
