# Generated by Django 6.0.1 on 2026-04-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_questionattempt_question_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='corrected',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='review_state',
            field=models.BooleanField(default=False),
        ),
    ]
