# Generated by Django 6.0.1 on 2026-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_questionattempt_corrected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
