# Generated by Django 6.0.1 on 2026-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_question_content_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_purpose',
            field=models.CharField(blank=True, default='practice', max_length=50, null=True),
        ),
    ]
