# Generated by Django 6.0.1 on 2026-05-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_question_question_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='stale',
            field=models.BooleanField(default=False),
        ),
    ]
