# Generated by Django 6.0.1 on 2026-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_assignment_assignmentstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
