# Generated by Django 6.0.1 on 2026-06-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_assignment_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('difficulty', models.SmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('easiness', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
