# Generated by Django 6.0.1 on 2026-06-12 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_card_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.quiz'),
        ),
    ]
