# Generated by Django 6.0.1 on 2026-06-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_card_easiness_remove_card_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='definition',
            field=models.TextField(blank=True, default=''),
        ),
    ]
