# Generated by Django 6.0.1 on 2026-07-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_card_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='video_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_segment_questions', to='api.videosegment'),
        ),
    ]
