# Generated by Django 6.0.1 on 2026-08-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_question_video_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='quiz',
        ),
    ]
