# Generated by Django 6.0.1 on 2026-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_card_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofspeech',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
