# Generated by Django 6.0.1 on 2026-08-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_partofspeech_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='part_of_speech',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
