# Generated by Django 6.0.1 on 2026-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_card_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofspeech',
            name='audio_blob',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
