# Generated by Django 6.0.1 on 2026-08-16 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_partofspeech_audio_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='api.sense'),
        ),
    ]
