# Generated by Django 6.0.1 on 2026-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_backfill_card_sense'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_staff',
            field=models.BooleanField(default=False),
        ),
    ]
