# Generated by Django 6.0.1 on 2026-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_profile_student_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictentry',
            name='hyphenated',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
