# Generated by Django 6.0.1 on 2026-09-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_dictentry_hyphenated'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofspeech',
            name='viet_pron_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
