# Generated by Django 6.0.1 on 2026-09-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_partofspeech_viet_pron_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partofspeech',
            name='viet_pron_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
