# Generated by Django 6.0.1 on 2026-09-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_partofspeech_viet_pron_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofspeech',
            name='viet_pron_regional_variant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
