# Generated by Django 6.0.1 on 2026-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_partofspeech_viet_pron_regional_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
